# Generated by Django 2.2 on 2019-06-01 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Food',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TouristSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tourist_Site_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='info_images')),
                ('detail', models.TextField()),
                ('phone', models.CharField(blank=True, help_text='optional', max_length=100, null=True)),
                ('mymap', models.CharField(blank=True, help_text='dont mind will work on it later', max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='hotel_img/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='hotel_img/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='hotel_img/%Y/%m/%d')),
                ('name', models.OneToOneField(help_text='select hotel ', on_delete=django.db.models.deletion.CASCADE, to='toresterngh.Attraction')),
                ('nearesthotel', models.ManyToManyField(blank=True, to='toresterngh.Hotel')),
            ],
            options={
                'verbose_name': 'About Attraction',
                'verbose_name_plural': 'About Attractions',
            },
        ),
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='info_images')),
                ('detail', models.TextField()),
                ('phone', models.CharField(blank=True, help_text='optional', max_length=100, null=True)),
                ('mymap', models.CharField(blank=True, help_text='dont mind will work on it later', max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='hotel_img/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='hotel_img/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='hotel_img/%Y/%m/%d')),
                ('name', models.OneToOneField(help_text='select hotel ', on_delete=django.db.models.deletion.CASCADE, to='toresterngh.Hotel')),
            ],
            options={
                'verbose_name': 'About Hotel',
                'verbose_name_plural': 'About Hotel',
            },
        ),
        migrations.CreateModel(
            name='FoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='info_images')),
                ('detail', models.TextField()),
                ('phone', models.CharField(blank=True, help_text='optional', max_length=100, null=True)),
                ('mymap', models.CharField(blank=True, help_text='dont mind will work on it later', max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='hotel_img/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='hotel_img/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='hotel_img/%Y/%m/%d')),
                ('name', models.OneToOneField(help_text='select hotel ', on_delete=django.db.models.deletion.CASCADE, to='toresterngh.Hotel')),
            ],
            options={
                'verbose_name': 'About Food',
                'verbose_name_plural': 'About Food',
            },
        ),
        migrations.CreateModel(
            name='AttractionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='info_images')),
                ('detail', models.TextField()),
                ('phone', models.CharField(blank=True, help_text='optional', max_length=100, null=True)),
                ('mymap', models.CharField(blank=True, help_text='dont mind will work on it later', max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='hotel_img/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='hotel_img/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='hotel_img/%Y/%m/%d')),
                ('name', models.OneToOneField(help_text='select Attraction', on_delete=django.db.models.deletion.CASCADE, to='toresterngh.Attraction')),
            ],
            options={
                'verbose_name': 'About Attraction',
                'verbose_name_plural': 'About Attraction',
            },
        ),
    ]
