# Generated by Django 2.2 on 2019-05-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toresterngh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='touristsite',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
