# Generated by Django 2.2 on 2019-06-02 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toresterngh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'verbose_name': 'Toursit Site', 'verbose_name_plural': 'Tourist Site'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tourist_site_info',
            options={'verbose_name': 'About Tourist Site', 'verbose_name_plural': 'About Tourist Sites'},
        ),
        migrations.AlterModelOptions(
            name='touristsite',
            options={},
        ),
        migrations.AlterField(
            model_name='attractioninfo',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourist_site_info',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourist_site_info',
            name='name',
            field=models.OneToOneField(help_text='select tourist site ', on_delete=django.db.models.deletion.CASCADE, to='toresterngh.Attraction'),
        ),
    ]
