# Generated by Django 2.2 on 2019-05-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toresterngh', '0002_auto_20190501_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Food', 'verbose_name_plural': 'Food'},
        ),
    ]
