# Generated by Django 2.2 on 2019-05-02 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toresterngh', '0003_auto_20190501_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attractioninfo',
            old_name='_map',
            new_name='mymap',
        ),
        migrations.RenameField(
            model_name='foodinfo',
            old_name='_map',
            new_name='mymap',
        ),
        migrations.RenameField(
            model_name='hotelinfo',
            old_name='_map',
            new_name='mymap',
        ),
        migrations.RenameField(
            model_name='tourist_site_info',
            old_name='_map',
            new_name='mymap',
        ),
    ]
