# Generated by Django 2.2 on 2019-05-30 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toresterngh', '0004_auto_20190502_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='number of children')),
                ('adult', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='number of adult')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('dateadd', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toresterngh.Tourist_Site_Info', verbose_name='toursite')),
            ],
        ),
    ]
