# Generated by Django 2.2 on 2019-05-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20190530_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(help_text='enter your email that we can reach you with', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.ForeignKey(help_text='select the site to book', on_delete=django.db.models.deletion.CASCADE, to='toresterngh.Tourist_Site_Info', verbose_name='toursite'),
        ),
    ]
