# Generated by Django 2.2 on 2019-06-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_booking_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
    ]
