# Generated by Django 2.2 on 2019-06-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20190602_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
