# Generated by Django 2.2 on 2019-06-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_booking_message_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-dateadd']},
        ),
    ]
