# Generated by Django 2.2 on 2019-06-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20190602_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_Guid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tourguid_img/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='request_guiid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Tour_Guid'),
        ),
    ]
