# Generated by Django 2.2 on 2019-06-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20190602_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour_guid',
            options={'verbose_name': 'Tour Guid', 'verbose_name_plural': 'Tour Guid'},
        ),
        migrations.RemoveField(
            model_name='tour_guid',
            name='name',
        ),
        migrations.AddField(
            model_name='tour_guid',
            name='t_name',
            field=models.CharField(default='Aggrey', max_length=200, verbose_name='name'),
        ),
    ]
