# Generated by Django 2.2 on 2019-06-02 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20190602_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_guid',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.ForeignKey(help_text='select the tour site to book', on_delete=django.db.models.deletion.CASCADE, to='toresterngh.Tourist_Site_Info', verbose_name='toursite'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='request_guiid',
            field=models.ForeignKey(blank=True, help_text='optional will assist you in your tour if selected', null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Tour_Guid'),
        ),
    ]
