# Generated by Django 2.2 on 2019-06-02 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20190602_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.ForeignKey(help_text='select the tour site to book', on_delete=django.db.models.deletion.DO_NOTHING, to='toresterngh.Tourist_Site_Info', verbose_name='toursite'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='request_guiid',
            field=models.OneToOneField(blank=True, help_text='optional select a tour guid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.Tour_Guid'),
        ),
    ]
